WebApplication4/Models/GioHang.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication4.Models
{
    public class GioHang
    {
        QuanLyBanSachEntities6 db = new QuanLyBanSachEntities6();
        public int iMaSach { get; set; }
        public string sTenSach { get; set; }
        public string sAnhBia { get; set; }
        public double dDonGia { get; set; }
        public int iSoLuong { get; set; }
        public double ThanhTien
        {
            get { return iSoLuong * dDonGia; }

        }
        // tạo giỏ hàng
        public GioHang(int MaSach)
        {
            iMaSach = MaSach;
            Sach sach = db.Saches.SingleOrDefault(n => n.MaSach == iMaSach);
            sTenSach = sach.TenSach;
            sAnhBia = sach.AnhBia;
            dDonGia = double.Parse(sach.GiaBan.ToString());
            iSoLuong = 1;
        }
    }
}

WebApplication4/Controllers/GioHangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication4.Models;
using System.Configuration;
using System.IO;
using System.Web.Script.Serialization;
using System.Data.Entity.ModelConfiguration.Conventions;
using System.Data.Entity;
using System.Net.Mail;
using System.Net;
using System.Security.Cryptography;
using System.Drawing;

namespace WebApplication4.Controllers
{
    public class GioHangController : Controller
    {
        QuanLyBanSachEntities6 db = new QuanLyBanSachEntities6();
        // Lấy giỏ hàng
        #region giỏ hàng
        public List<GioHang> LayGioHang()
        {
            List<GioHang> listGioHang = Session["GioHang"] as List<GioHang>;
            if (listGioHang == null)   // nếu giỏ hàng chưa tồn tại thì tạo ra listgiohang
            {
                listGioHang = new List<GioHang>();
                Session["GioHang"] = listGioHang;
            }
            return listGioHang;
        }
        // thêm giỏ hàng
        public ActionResult ThemGioHang(int iMaSach, string strURL)
        {
            Sach sach = db.Saches.SingleOrDefault(n => n.MaSach == iMaSach);
            if (sach == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            List<GioHang> listGioHang = LayGioHang();
            GioHang Sach = listGioHang.Find(n => n.iMaSach == iMaSach);
            if (Sach == null)
            {
                Sach = new GioHang(iMaSach);
                listGioHang.Add(Sach);
                return Redirect(strURL);
            }
            else
            {
                Sach.iSoLuong++;
                return Redirect(strURL);
            }
        }
        // cập nhật giỏ hàng
        public ActionResult CapNhatGioHang(int iMaSach, FormCollection f)
        {
            Sach sach = db.Saches.SingleOrDefault(n => n.MaSach == iMaSach);
            if (sach == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            List<GioHang> listGioHang = LayGioHang();
            GioHang sanpham = listGioHang.SingleOrDefault(n => n.iMaSach == iMaSach);
            if (sanpham != null)
            {
                sanpham.iSoLuong = int.Parse(f["txtSoLuong"].ToString());

            }
            return RedirectToAction("GioHang");

        }
        // Xóa giỏ hàng
        public ActionResult XoaGioHang(int iMaSach)
        {
            Sach sach = db.Saches.SingleOrDefault(n => n.MaSach == iMaSach);
            if (sach == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            List<GioHang> listGioHang = LayGioHang();
            GioHang sanpham = listGioHang.SingleOrDefault(n => n.iMaSach == iMaSach);
            if (sanpham != null)
            {
                listGioHang.RemoveAll(n => n.iMaSach == iMaSach);

            }
            if (listGioHang.Count == 0)
            {
                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction("GioHang");
        }
        // xây dựng giỏ hàng
        public ActionResult GioHang()
        {
            if (Session["GioHang"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            List<GioHang> listGioHang = LayGioHang();

            return View(listGioHang);
        }
        // tinh tong so luong va tong tien
        public double TongTien()
        {
            double dTongTien = 0;
            List<GioHang> listGioHang = Session["GioHang"] as List<GioHang>;
            if (listGioHang != null)
            {
                dTongTien = listGioHang.Sum(n => n.ThanhTien);
            }
            return dTongTien;
        }
        private int TongSoLuong()
        {
            int iTongSoLuong = 0;
            List<GioHang> lstGioHang = Session["GioHang"] as List<GioHang>;
            if (lstGioHang != null)
            {
                iTongSoLuong = lstGioHang.Sum(n => n.iSoLuong);
            }
            return iTongSoLuong;
        }
        // Tạo Parial Giỏ Hàng
        public ActionResult GioHangPartial()
        {
            if (TongSoLuong() == 0)
            {
                return PartialView();
            }
            ViewBag.TongSoLuong = TongSoLuong();
            ViewBag.TongTien = TongTien();
            return PartialView();
        }
        // xây dựng 1 view cho người  dùng chình sửa giỏ hàng
        public ActionResult SuaGioHang()
        {

            if (Session["GioHang"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            List<GioHang> listGioHang = LayGioHang();

            return View(listGioHang);
        }
        #endregion
        #region đặt hàng
        // xây dựng giỏ hàng
        double tongtien = 0;
        [HttpPost]
        public ActionResult DatHang()
        {
            try
            {
                // kiểm tra đăng nhập
                if (Session["TaiKhoan"] == null || Session["TaiKhoan"].ToString() == null)
                {
                    return RedirectToAction("DangNhap", "DangKyDangNhap");
                }
                // kiểm tra giỏ hàng
                if (Session["GioHang"] == null || Session["GioHang"] == "")
                {
                    return RedirectToAction("Index", "Home");
                }
                // thêm đơn hàng
                DonHang dh = new DonHang();
                KhachHang kh = (KhachHang)Session["TaiKhoan"];
                List<GioHang> gh = LayGioHang();
                if (kh != null)
                {
                    dh.MaKH = kh.MaKH;
                    dh.NgayDat = DateTime.Now;
                }
                db.DonHangs.Add(dh);
                db.SaveChanges();
                foreach (var item in gh)
                {
                    ChiTietDonHang ctdh = new ChiTietDonHang();
                    ctdh.MaDonHang = dh.MaDonHang;
                    ctdh.MaSach = item.iMaSach;
                    ctdh.SoLuong = item.iSoLuong;
                    ctdh.DonGia = item.dDonGia.ToString();
                    db.ChiTietDonHangs.Add(ctdh);
                    tongtien += item.dDonGia*item.iSoLuong;
                }
                db.SaveChanges();
                GuiMailDatHang(kh, dh.MaDonHang);
                return RedirectToAction("DatHangThanhCong");
            }catch { return View(); }
        }
        
        string nguoigui = "Quan96kun@gmail.com";
        string matkhau = "Quan19101996";
        string nguoinhan = "";
        string tieude1 = "";
        string tieude2 = "";
        string tinnhan = "";
        void GuiMailDatHang(KhachHang kh,int madonhang,Attachment file = null)
        {
            nguoinhan = kh.Email;
            tieude1 = "Thông tin đơn đặt hàng từ khách hàng " + kh.HoTen+" -Shop Bán sách NVQ";
            tieude2 = "Đơn hàng mới từ khách hàng " + kh.HoTen + " -Shop Bán sách NVQ";
            string filenameImage = @"D:\hinh anh web ban sach\hình ảnh về trang liên kết\h2.jpg";
            tinnhan ="\nThông tin đơn đặt hàng :\nHọ Tên :"+kh.HoTen+"\nĐịa chỉ : "+kh.DiaChi+"\nSố điện thoại : "+kh.DienThoai+"\nMã đơn hàng : "+madonhang+"\nTổng giá trị đơn hàng : "+tongtien+"\n\n\n\n\nShop bán sách NVQ-Niềm vui mua sắm cho mọi người\nĐịa chỉ : 134 Trương Định - Hai Bà Trưng , Hà Nội ";
            MailMessage message1 = new MailMessage(nguoigui, nguoinhan, tieude1, tinnhan);
            MailMessage message2 = new MailMessage(nguoigui, nguoigui, tieude2, tinnhan);
            message1.Attachments.Add(new Attachment(filenameImage));
            message2.Attachments.Add(new Attachment(filenameImage));
            SmtpClient client = new SmtpClient("smtp.gmail.com", 587);
            client.EnableSsl = true;
            client.Credentials = new NetworkCredential(nguoigui, matkhau);
            client.Send(message1);
            client.Send(message2);
        }
        void GuiMailDatHang_co_file_dinh_kem(KhachHang kh, int madonhang, Attachment file = null)
        {
            nguoinhan = kh.Email;
            tieude1 = "Thông tin đơn đặt hàng từ khách hàng " + kh.HoTen + " -Shop Bán sách NVQ";
            tieude2 = "Đơn hàng mới từ khách hàng " + kh.HoTen + " -Shop Bán sách NVQ";
            string filenameImage = @"D:\hinh anh web ban sach\hình ảnh về trang liên kết\h2.jpg";
            tinnhan ="\nThông tin đơn đặt hàng :\nHọ Tên :" + kh.HoTen + "\nĐịa chỉ : " + kh.DiaChi + "\nSố điện thoại : " + kh.DienThoai + "\nMã đơn hàng : " + madonhang + "\nTổng giá trị đơn hàng : " + tongtien + "\n\n\n\n\nShop bán sách NVQ-Niềm vui mua sắm cho mọi người\nĐịa chỉ : 134 Trương Định - Hai Bà Trưng , Hà Nội ";
            

            using (MailMessage mail1= new MailMessage())
            {
                mail1.From = new MailAddress(nguoigui);
                mail1.To.Add(nguoigui);
                mail1.Subject = tieude1;
                mail1.Body = tinnhan;
                mail1.Attachments.Add(new Attachment(filenameImage));
                SmtpClient client = new SmtpClient("smtp.gmail.com", 587);
                client.EnableSsl = true;
                client.Credentials = new NetworkCredential(nguoigui, matkhau);
                client.Send(mail1);

            }
            using (MailMessage mail2 = new MailMessage())
            {
                mail2.From = new MailAddress(nguoigui);
                mail2.To.Add(nguoinhan);
                mail2.Subject = tieude2;
                mail2.Body = tinnhan;
                mail2.IsBodyHtml = true;
                mail2.Attachments.Add(new Attachment(filenameImage));
                SmtpClient client = new SmtpClient("smtp.gmail.com", 587);
                client.EnableSsl = true;
                client.Credentials = new NetworkCredential(nguoigui, matkhau);
                client.Send(mail2);

            }

WebApplication4/Controllers/NguoiDungController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication4.Models;

namespace WebApplication4.Controllers
{
    public class NguoiDungController : Controller
    {
        // GET: NguoiDung
        QuanLyBanSachEntities6 db = new QuanLyBanSachEntities6();
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult DangKy()
        {
            return View();
        }
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult DangKy(KhachHang kh, FormCollection f)
        {
            KhachHang timkiemKhachHang = db.KhachHangs.SingleOrDefault(n => n.TaiKhoan == kh.TaiKhoan);
            if (timkiemKhachHang != null)
            {
                ViewBag.ThongBaoKT = "Tên tài khoản đã tồn tại trong cơ sở dữ liệu , xin vui lòng kiểm tra lại !";
                return View();
            }
            if(f["txtMK"].ToString()!=null && f["txtMK"].ToString() != "")
            {
                kh.MatKhau = f["txtMK"].ToString();
            }
            else
            {
                ViewBag.TB = "Chưa nhập mật khẩu ";
                return View();
            }
            if (ModelState.IsValid)
            {
                Session["TKDk"] = kh.TaiKhoan;
                Session["MKDK"] = kh.MatKhau;
                db.KhachHangs.Add(kh);
                db.SaveChanges();
                return RedirectToAction("DangNhap","DangKyDangNhap");
            }
            return View();
        }
        [HttpGet]
        public ActionResult DangNhap()
        {
            return View();
        }
        [HttpPost]
        public ActionResult DangNhap(FormCollection f)
        {
            string sTaiKhoan = f["txtTaiKhoan"].ToString();
            string sMatKhau = f.Get("txtMatKhau").ToString();
            KhachHang kh = db.KhachHangs.SingleOrDefault(n => n.TaiKhoan == sTaiKhoan && n.MatKhau == sMatKhau);
            TaiKhoanAdmin admin = db.TaiKhoanAdmins.SingleOrDefault(n => n.TaiKhoan == sTaiKhoan && n.MatKhau == sMatKhau);
            if (kh != null && admin == null)
            {
                Session["TaiKhoan"] = kh;
                Session["username"] = kh.HoTen;
                return RedirectToAction("Index", "Home");
            }
            if (kh == null && admin != null)
            {
                Session["TaiKhoan"] = admin;
                Session["username"] = admin.HoTen;
                return RedirectToAction("Index", "QuanLySanPham");
            }
               
            ViewBag.ThongBao = "Tên tài khoản hoặc mật khẩu không đúng";
            return View();
        }
        public ActionResult Thoat()
        {
            Session["TaiKhoan"] = null;
            Session["username"] = null;
            Session["TKDk"] = null;
            Session["MKDK"] = null;
            Session["GioHang"] = "";
            return RedirectToAction("Index","Home");
        }
    }
}

WebApplication4/Controllers/SachController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication4.Models;

namespace WebApplication4.Controllers
{
    public class SachController : Controller
    {
        //
        // GET: /SachMoiPartial/
        QuanLyBanSachEntities6 db = new QuanLyBanSachEntities6();
        public PartialViewResult SachMoiPartial()
        {
            var lstSachMoi = db.Saches.Take(3).ToList();
            return PartialView(lstSachMoi);
        }
        //Xem chi tiết
        public ViewResult XemChiTiet(int MaSach = 0)
        {
            Sach sach = db.Saches.SingleOrDefault(n => n.MaSach == MaSach);
            if (sach == null)
            {
                //Trả về trang báo lỗi 
                Response.StatusCode = 404;
                return null;
            }
            //ChuDe cd = db.ChuDes.Single(n => n.MaChuDe == sach.MaChuDe);
            //ViewBag.TenCD = cd.TenChuDe;
            ViewBag.TenChuDe = db.ChuDes.Single(n => n.MaChuDe == sach.MaChuDe).TenChuDe;
            ViewBag.NhaXuatBan = db.NhaXuatBans.Single(n => n.MaNXB == sach.MaNXB).TenNXB;
            return View(sach);
        }
    }
}

WebApplication4/Views/GioHang/DangNhapPartial.cshtml
    @if (Session["TaiKhoan"] != null)
    {
            
            @Html.ActionLink(""+Session["username"],"HienThiTaiKhoan", "DangKyDangNhap", null, htmlAttributes: new { })
            <a href="#">/</a>
            <i class="fa fa-sign-in"></i>
            @Html.ActionLink(" Thoát", "Thoat", "NguoiDung", null, htmlAttributes: new { @class = "Thoat" })

    }
    else
    {
            <i class="fa fa-sign-in"></i>
            @Html.ActionLink("Đăng ký", "DangKy", "NguoiDung", null, htmlAttributes: new { @class = "DangKy" })
            <i class="fa fa-unlock"></i>
            @Html.ActionLink("Đăng nhập", "DangNhap", "DangKyDangNhap", null, htmlAttributes: new { @class = "DangNhap" })

    }

WebApplication4/Views/GioHang/DatHangThanhCong.cshtml
@{
    ViewBag.Title = "DatHangThanhCong";
    Layout = "~/Views/Layout/NguoiDungLayout.cshtml";
}
<div style="border-top:solid 1px #9f9696;margin-left:200px;color:red"><h2>Đặt hàng thành công</h2> </div>
<div style="margin-left:200px;"> Quý khách hãy đợi để nhân viên của cửa hàng xử lý và gửi thông tin vào e-mail hoặc liên lạc cho quý khách
    chậm nhất là sau 2 ngày <br/>
    Mọi thắc mắ xin quý khách hãy gửi về địa chỉ e-mail :Quan96kun@gmail.com  Hotline :0168454008<br/>
    hoặc đến cửa hàng đại lý gần nhất để giải quyết<br/>
    Chân thành cảm ơn đã sử dụng dịch vụ của chúng tôi ...!</div>

WebApplication4/Views/GioHang/GioHang.cshtml
@using WebApplication4.Models
@model List<GioHang>
@{
    ViewBag.Title = "GioHang";
    Layout = "~/Views/Layout/NguoiDungLayout.cshtml";
}

<h2>Giỏ hàng của bạn</h2>
@{ int tonggiatri = 0;}
<table id="divGioHang">
    <tr>
        <td>Mã sách</td>

        <td>Tên sách</td>

        <td>Ảnh bìa</td>

        <td>Đơn giá</td>


        <td>Số lượng</td>

        <td>Thành tiền</td>
    </tr>


    @foreach (var item in Model)
    {
        int dg = int.Parse(item.dDonGia.ToString());
        int sl = item.iSoLuong;
        tonggiatri = tonggiatri + dg * sl;
        <tr>
            <td style="width:150px;">@item.iMaSach</td>

            <td style="width:500px;">@item.sTenSach</td>

            <td style="width:250px;"><a href="@Url.Action("XemChiTiet", "Sach", new { @MaSach = item.iMaSach})"><img src="@Url.Content("~/HinhAnhSP/"+item.sAnhBia)" width="80" height="100" /></a></td>

            <td style="width:250px;">
                @String.Format("{0:0,0}", item.dDonGia) VNĐ
            </td>

            <td style="width:250px;">@item.iSoLuong</td>

            <td style="width:250px;">@String.Format("{0:0,0}", item.ThanhTien) VNĐ</td>

        </tr>

    }
    <tr>
        <td colspan="6" style="text-align:right;color:black ;">
            Tổng giá trị : @tonggiatri
        </td>

    </tr>

    <tr>
        <td colspan="6" style="text-align:right;color:blue ;">
            @Html.ActionLink("Chỉnh sửa giỏ hàng", "SuaGioHang")
        </td>

    </tr>
    <tr>
        <td colspan="6" style="text-align:right;color:blue">
            @using (Html.BeginForm("DatHang", "GioHang"))
            {
                <input type="submit" value="Đặt hàng" />
            }
        </td>
    </tr>
</table>
@*Css giỏ hàng*@
<style>
    #divGioHang {
        border: 1px solid #808080;
        margin-left: 5%;
    }

        #divGioHang td {
            padding: 10px;
            border: 1px solid #808080;
        }
</style>

WebApplication4/Views/GioHang/GioHangPartial.cshtml
    <a href="@Url.Action("GioHang", "GioHang")">
        <i class="fa fa-shopping-cart">Giỏ hàng của bạn</i>
        (@ViewBag.TongSoLuong)
    </a>

WebApplication4/Views/GioHang/SuaGioHang.cshtml
@using WebApplication4.Models
@model List<GioHang>
@{
    ViewBag.Title = "Sửa giỏ hàng";
    Layout = "~/Views/Layout/NguoiDungLayout.cshtml";
}

<h2>Giỏ hàng của bạn</h2>
<table id="divGioHang">
    <tr>
        <td>Mã sách</td>

        <td>Tên sách</td>

        <td>Ảnh bìa</td>

        <td>Đơn giá</td>


        <td>Số lượng</td>

        <td>Thành tiền</td>
    </tr>


    @foreach (var item in Model)
    {

        <tr>
            <td style="width:150px;">@item.iMaSach</td>

            <td style="width:500px;">@item.sTenSach</td>

            <td style="width:250px;"><img src="@Url.Content("~/HinhAnhSP/"+item.sAnhBia)" width="80" height="100" /></td>

            <td style="width:250px;">
                @String.Format("{0:0,0}", item.dDonGia) VNĐ
            </td>
            @*Chỉnh sửa giỏ hàng gọi về action CapNhatGioHang*@
                @using (Html.BeginForm("CapNhatGioHang", "GioHang", new { @iMaSach = item.iMaSach }))
                {
                    <td style="width:100px; color:#808080;margin-left:40px;">@Html.TextBox("txtSoLuong", item.iSoLuong) </td>




                    <td>@String.Format("{0:0,0}", item.ThanhTien) VNĐ</td>
                    <td>
                        <input type="submit" value="Cập nhật" style="margin-left:10px;" />
                        <br />
                        @*Xóa giỏ hàng gọi về Action XoaGioHang*@
                        @Html.ActionLink("Xóa", "XoaGioHang", new { @iMaSach = item.iMaSach })
                    </td>
                }
            <td></td>
        </tr>

    }
</table>
@*Css giỏ hàng*@
<style>
    #divGioHang {
        border: 1px solid #808080;
        margin-left: 10%;
    }

        #divGioHang td {
            padding: 10px;
            border: 1px solid #808080;
        }
</style>