WebApplication4/Controllers/QuanLyChuDeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;
using WebApplication4.Models;

namespace WebApplication4.Controllers
{
    public class QuanLyChuDeController : Controller
    {
        // GET: QuanLyChuDe
        QuanLyBanSachEntities6 db = new QuanLyBanSachEntities6();
        public ActionResult Index(int? page)
        {
            int pageSize = 20;
            int pageNumber = (page ?? 1);
            return View(db.ChuDes.ToList().OrderBy(n => n.MaChuDe).ToPagedList(pageNumber, pageSize));
        }
        // thêm mới
        [HttpGet]
        public ActionResult ThemMoi()
        {
            return View();
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult ThemMoi(ChuDe ChuDe)
        {
            ChuDe timkiemNXB = db.ChuDes.SingleOrDefault(n => n.TenChuDe == ChuDe.TenChuDe);
            if (timkiemNXB != null)
            {
                ViewBag.ThongBaoKT = "Tên chủ đề đã tồn tại trong cơ sở dữ liệu , xin vui lòng kiểm tra lại !";
                return View();
            }
            if (ModelState.IsValid)
            {
                db.ChuDes.Add(ChuDe);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
        // chinh sửa săn phẩm
        [HttpGet]
        public ActionResult ChinhSua(int MaChuDe)
        {

            ChuDe NXB = db.ChuDes.SingleOrDefault(n => n.MaChuDe == MaChuDe);
            if (NXB == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(NXB);
        }
        //update dữ liệu chỉnh sửa
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult ChinhSua(ChuDe NXB, FormCollection f)
        {
            ChuDe timkiemsach = db.ChuDes.SingleOrDefault(n => n.TenChuDe == NXB.TenChuDe);
            if (timkiemsach != null)
            {
                ViewBag.ThongBaoKT = "Tên chủ đề đã tồn tại trong cơ sở dữ liệu , xin vui lòng kiểm tra lại !";
                return View(timkiemsach);
            }
            if (ModelState.IsValid)
            {
                db.Entry(NXB).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            }

            return RedirectToAction("Index");
        }
        // thêm mới sách
        public ActionResult HienThi(int MaChuDe)
        {

            ChuDe NXB = db.ChuDes.SingleOrDefault(n => n.MaChuDe == MaChuDe);
            if (NXB == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(NXB);
        }
        // xóa sách
        public ActionResult Xoa(int MaChuDe)
        {

            ChuDe NXB = db.ChuDes.SingleOrDefault(n => n.MaChuDe == MaChuDe);
            if (NXB == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(NXB);
        }
        [HttpPost, ActionName("Xoa")]
        public ActionResult XacNhanXoa(int MaChuDe)
        {

            ChuDe NXB = db.ChuDes.SingleOrDefault(n => n.MaChuDe == MaChuDe);
            if (NXB == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            List<Sach> timkiemsach = db.Saches.Where(n => n.ChuDe.MaChuDe == MaChuDe).ToList();
            if (timkiemsach.Count != 0)
            {
                ViewBag.ThongBaoKT = "Vẫn còn sách của chủ đề này trong cơ sở dữ liệu , xin vui lòng kiểm tra lại !";
                return View(NXB);
            }
            db.ChuDes.Remove(NXB);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

WebApplication4/Views/QuanLyChuDe/ChinhSua.cshtml
@model WebApplication4.Models.ChuDe

@{
    ViewBag.Title = "ChinhSua";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<h2 style="color:red">Chỉnh sửa</h2>

@using (Html.BeginForm("ChinhSua", "QuanLyChuDe", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Chủ đề</h4>
        <h3 style="color:red">@ViewBag.ThongBaoKT</h3>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MaChuDe, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <span style="font-size:15pt;margin-top:2px;margin-left:5px">@Model.MaChuDe</span>
                @Html.Hidden("MaChuDe", Model.MaChuDe)
            </div>
        </div>
        <br />
        <div class="form-group">
            @Html.LabelFor(model => model.TenChuDe, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenChuDe, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenChuDe, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay trở về", "Index")
</div>

WebApplication4/Views/QuanLyChuDe/HienThi.cshtml
@model WebApplication4.Models.ChuDe

@{
    ViewBag.Title = "HienThi";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<h2 style="color:red">Hiển thị </h2>

<div>
    <h4>Chủ đề</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MaChuDe)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MaChuDe)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TenChuDe)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TenChuDe)
        </dd>
    </dl>
</div>
<br/><br /><br />
<p>
    @Html.ActionLink("Trở về", "Index")  |
    @Html.ActionLink("Chỉnh sửa", "ChinhSua", new { @MaChude = Model.MaChuDe })
</p>

WebApplication4/Views/QuanLyChuDe/Index.cshtml
@using PagedList;
@using PagedList.Mvc;


@model PagedList.PagedList<WebApplication4.Models.ChuDe>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<h2 style="color:red">Quản lý chủ đề</h2>

<p>
    @Html.ActionLink("Thêm mới", "ThemMoi")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.First().MaChuDe)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().TenChuDe)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.MaChuDe)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TenChuDe)
        </td>
        <td>
            @Html.ActionLink("Sửa", "ChinhSua", new { @MaChuDe = item.MaChuDe }) |
            @Html.ActionLink("Hiển Thị", "HienThi", new { @MaChuDe = item.MaChuDe }) |
            @Html.ActionLink("Xóa", "Xoa", new { @MaChuDe = item.MaChuDe })
    </tr>
}

</table>
Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/@Model.PageCount
<div class="MenuTrang">
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))
</div>
<style>
    .MenuTrang li {
        display: inline;
    }
</style>

WebApplication4/Views/QuanLyChuDe/ThemMoi.cshtml
@model WebApplication4.Models.ChuDe

@{
    ViewBag.Title = "ThemMoi";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<h2 style="color:red">Thêm mới</h2>
<br /><br /><br /><br />
@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Chủ đề</h4>
        <h3 style="color:red">@ViewBag.ThongBaoKT</h3>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.TenChuDe, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenChuDe, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenChuDe, "", new { @class = "text-danger" })
            </div>
        </div>
        <br/>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay trở về", "Index")
</div>

WebApplication4/Views/QuanLyChuDe/Xoa.cshtml
@model WebApplication4.Models.ChuDe

@{
    ViewBag.Title = "Xoa";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}


<h3 style="color:red">Bạn có chắc chắn muốn xóa chủ đề này không?</h3>
<div>
    <h4>Chủ đề</h4>
    <h3 style="color:red">@ViewBag.ThongBaoKT</h3>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MaChuDe)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MaChuDe)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TenChuDe)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TenChuDe)
        </dd>
    </dl>
    <br/><br /><br />
    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xóa" class="btn btn-default" /> |
            @Html.ActionLink("Quay trở về", "Index")
        </div>
    }
</div>