WebApplication4/Controllers/QuanLySanPhamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication4.Models;
using PagedList;
using PagedList.Mvc;
using System.IO;

namespace WebApplication4.Controllers
{
    public class QuanLySanPhamController : Controller
    {
        // GET: QuanLySanPham
        QuanLyBanSachEntities6 db = new QuanLyBanSachEntities6();
        NguoiDungController nd = new NguoiDungController();
        public ActionResult Index(int? page)
        {
            try
            {
                if (Session["taikhoan"]==null||Session["taikhoan"]=="")
                {
                    Response.StatusCode = 404;
                    return null;
                }
            }catch {
                Response.StatusCode = 404;
                return null;
            }
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(db.Saches.ToList().OrderBy(n => n.MaSach).ToPagedList(pageNumber, pageSize));
        }
        // thêm mới
        [HttpGet]
        public ActionResult ThemMoi()
        {
            try
            {
                if (Session["taikhoan"] == null || Session["taikhoan"] == "")
                {
                    Response.StatusCode = 404;
                    return null;
                }
            }
            catch
            {
                Response.StatusCode = 404;
                return null;
            }
            // đưa dữ liệu vào dropdownlist
            ViewBag.MaChuDe = new SelectList(db.ChuDes.ToList().OrderBy(n => n.TenChuDe), "MaChuDe", "TenChuDe");
            ViewBag.MaNXB = new SelectList(db.NhaXuatBans.ToList().OrderBy(n => n.TenNXB), "MaNXB", "TenNXB");
            return View();
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult ThemMoi(Sach sach, HttpPostedFileBase fileUpload)
        {
            ViewBag.MaChuDe = new SelectList(db.ChuDes.ToList().OrderBy(n => n.TenChuDe), "MaChuDe", "TenChuDe");
            ViewBag.MaNXB = new SelectList(db.NhaXuatBans.ToList().OrderBy(n => n.TenNXB), "MaNXB", "TenNXB");
            Sach timkiemsach = db.Saches.SingleOrDefault(n => n.TenSach == sach.TenSach);
            if(timkiemsach != null)
            {
                ViewBag.ThongBaoKT = "Tên sách đã tồn tại trong cơ sở dữ liệu , xin vui lòng kiểm tra lại !";
                return View();
            }

            if (fileUpload == null)
            {
                ViewBag.ThongBao = "Chưa chọn hình ảnh !";
                return View();
            }
            if (ModelState.IsValid)
            {
                // lưu tên
                var fileName = Path.GetFileName(fileUpload.FileName);
                // lưu đường dẫn
                var path = Path.Combine(Server.MapPath("~/HinhAnhSP"), fileName);
                if (System.IO.File.Exists(path))
                {
                    ViewBag.ThongBao = "Hình ảnh đã tồn tại !";
                }
                else
                {
                    fileUpload.SaveAs(path);
                }
                sach.AnhBia = fileUpload.FileName;
                db.Saches.Add(sach);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
        // chinh sửa săn phẩm
        [HttpGet]
        public ActionResult ChinhSua(int MaSach)
        {
            try
            {
                if (Session["taikhoan"] == null || Session["taikhoan"] == "")
                {
                    Response.StatusCode = 404;
                    return null;
                }
            }
            catch
            {
                Response.StatusCode = 404;
                return null;
            }
            Sach sach = db.Saches.SingleOrDefault(n => n.MaSach == MaSach);
            if (sach == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            ViewBag.MaChuDe = new SelectList(db.ChuDes.ToList().OrderBy(n => n.TenChuDe), "MaChuDe", "TenChuDe",sach.MaChuDe);
            ViewBag.MaNXB = new SelectList(db.NhaXuatBans.ToList().OrderBy(n => n.TenNXB), "MaNXB", "TenNXB",sach.MaNXB);
            return View(sach);
        }
        //update dữ liệu chỉnh sửa
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult ChinhSua(Sach sach, HttpPostedFileBase fileUpload,FormCollection f)
        {
            ViewBag.MaChuDe = new SelectList(db.ChuDes.ToList().OrderBy(n => n.TenChuDe), "MaChuDe", "TenChuDe", sach.MaChuDe);
            ViewBag.MaNXB = new SelectList(db.NhaXuatBans.ToList().OrderBy(n => n.TenNXB), "MaNXB", "TenNXB", sach.MaNXB);
            Sach timkiemsach = db.Saches.SingleOrDefault(n => n.TenSach == sach.TenSach);
            if (timkiemsach != null)
            {
                Sach sachtk = db.Saches.SingleOrDefault(n => n.TenSach == sach.TenSach && n.MaChuDe == sach.MaChuDe && n.MaNXB == sach.MaNXB && n.MoTa == sach.MoTa && n.GiaBan == sach.GiaBan);
                if (sachtk == null)
                {
                    ViewBag.ThongBaoKT = "Tên sách đã tồn tại trong cơ sở dữ liệu , xin vui lòng kiểm tra lại !";
                    return View(timkiemsach);
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }
            else
            {
                if (fileUpload != null)
                {
                    // lưu tên
                    var fileName = Path.GetFileName(fileUpload.FileName);
                    // lưu đường dẫn
                    var path = Path.Combine(Server.MapPath("~/HinhAnhSP"), fileName);
                    if (System.IO.File.Exists(path))
                    {

                    }
                    else
                    {
                        fileUpload.SaveAs(path);
                    }
                    sach.AnhBia = fileUpload.FileName;
                    if (ModelState.IsValid)
                    {
                        db.Entry(sach).State = System.Data.Entity.EntityState.Modified;
                        db.SaveChanges();
                    }
                }
                else
                {
                    string sMatKhau = f.Get("abc").ToString();
                    sach.AnhBia = sMatKhau;
                    if (ModelState.IsValid)
                    {
                        db.Entry(sach).State = System.Data.Entity.EntityState.Modified;
                        db.SaveChanges();
                    }
                }
            }
            return RedirectToAction("Index");
        }
        // thêm mới sách
        public ActionResult HienThi(int MaSach)
        {
            try
            {
                if (Session["taikhoan"] == null || Session["taikhoan"] == "")
                {
                    Response.StatusCode = 404;
                    return null;
                }
            }
            catch
            {
                Response.StatusCode = 404;
                return null;
            }
            Sach sach = db.Saches.SingleOrDefault(n => n.MaSach == MaSach);
            if (sach == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(sach);
        }
        // xóa sách
        public ActionResult Xoa(int MaSach)
        {
            try
            {
                if (Session["taikhoan"] == null || Session["taikhoan"] == "")
                {
                    Response.StatusCode = 404;
                    return null;
                }
            }
            catch
            {
                Response.StatusCode = 404;
                return null;
            }
            Sach sach = db.Saches.SingleOrDefault(n => n.MaSach == MaSach);
            if (sach == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(sach);
        }
        [HttpPost,ActionName("Xoa")]
        public ActionResult XacNhanXoa(int MaSach)
        {

            Sach sach = db.Saches.SingleOrDefault(n => n.MaSach == MaSach);
            if (sach == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            db.Saches.Remove(sach);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

WebApplication4/Views/QuanLySanPham/ChinhSua.cshtml
@model WebApplication4.Models.Sach

@{
    ViewBag.Title = "ChinhSua";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<h2 style="color:red">Chỉnh sửa</h2>

@using (Html.BeginForm("ChinhSua", "QuanLySanPham", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Sách</h4>
        <h3 style="color:red">@ViewBag.ThongBaoKT</h3>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MaSach, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <span style="font-size:15pt;margin-top:2px;margin-left:5px">@Model.MaSach</span>
                @Html.Hidden("MaSach", Model.MaSach)
            </div>
        </div>
        <br />
        <div style="display:none">@Html.TextBox("abc", "" + Model.AnhBia)</div>
        <div class="form-group">
            @Html.LabelFor(model => model.TenSach, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenSach, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenSach, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />
        <div class="form-group">
            @Html.LabelFor(model => model.GiaBan, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GiaBan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GiaBan, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />
        <div class="form-group">
            @Html.LabelFor(model => model.AnhBia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <img src="@Url.Content("~/HinhAnhSP/" + Model.AnhBia)" width="100" height="150" />
                <div style="margin-left:150px">
                    <input type="file" name="fileUpload" />
                </div>
            </div>
        </div>
        <br />
        <div class="form-group">
            @Html.LabelFor(model => model.NgayCapNhat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.NgayCapNhat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgayCapNhat, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />
        <div class="form-group">
            @Html.LabelFor(model => model.SoLuongTon, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoLuongTon, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoLuongTon, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />
        <div class="form-group">
            @Html.LabelFor(model => model.MaNXB, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaNXB")
            </div>
        </div>
        <br />
        <div class="form-group">
            @Html.LabelFor(model => model.MaChuDe, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaChuDe")
            </div>
        </div>
        <br />
        <div class="form-group">
            @Html.LabelFor(model => model.Moi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Moi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Moi, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />
        <div class="form-group">
            @Html.LabelFor(model => model.MoTa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <textarea name="MoTa">@Model.MoTa</textarea>
            </div>
        </div>
        <br /><br />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="lưu" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay trở về", "Index")
</div>

WebApplication4/Views/QuanLySanPham/HienThi.cshtml
@model WebApplication4.Models.Sach

@{
    ViewBag.Title = "HienThi";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<h2 style="color:red"> Hiển thị</h2>

<div>
    <h4>Sách</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MaSach)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaSach)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TenSach)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenSach)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GiaBan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GiaBan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MoTa)
        </dt>

        <dd>
            @Html.Raw(Model.MoTa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AnhBia)
        </dt>

        <dd>
            <img src="@Url.Content("~/HinhAnhSP/"+Model.AnhBia)" width="100" height="150" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgayCapNhat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayCapNhat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoLuongTon)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoLuongTon)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MaNXB)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NhaXuatBan.TenNXB)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MaChuDe)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ChuDe.TenChuDe)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Moi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Moi)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Trở về", "Index")  |  
    @Html.ActionLink("Chỉnh sửa", "ChinhSua", new { @MaSach = Model.MaSach })
</p>

WebApplication4/Views/QuanLySanPham/Index.cshtml
@using PagedList;
@using PagedList.Mvc;


@model PagedList.PagedList<WebApplication4.Models.Sach>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<h2 style="color:red">Quản lý sách</h2>

<p>
    @Html.ActionLink("Thêm sách mới", "ThemMoi")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.First().MaSach)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().TenSach)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().GiaBan)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().MoTa)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().AnhBia)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().NgayCapNhat)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().SoLuongTon)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().MaNXB)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().MaChuDe)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Moi)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.MaSach)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TenSach)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.GiaBan)
        </td>
        <td>
            <div style="width:250px">@Html.Raw(item.MoTa)</div>
        </td>
        <td>
            <div id="AnhBia"><img src="@Url.Content("~/HinhAnhSP/"+item.AnhBia)" width="100" height="150" /></div>
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NgayCapNhat)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SoLuongTon)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NhaXuatBan.TenNXB)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ChuDe.TenChuDe)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Moi)
        </td>
        <td>
            @Html.ActionLink("Sửa", "ChinhSua", new { @MaSach=item.MaSach}) |
            @Html.ActionLink("Hiển Thị", "HienThi", new { @MaSach = item.MaSach }) |
            @Html.ActionLink("Xóa", "Xoa", new { @MaSach = item.MaSach })
        </td>
    </tr>
}

</table>
Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/@Model.PageCount
<div class="MenuTrang">
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))
</div>
<style>
    .MenuTrang li {
        display: inline;
    }
</style>

WebApplication4/Views/QuanLySanPham/ThemMoi.cshtml
@model WebApplication4.Models.Sach

@{
    ViewBag.Title = "ThemMoi";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<h2 style="color:red">Thêm Mới</h2>

@*thêm thuộc tính cho form để upload ảnh*@
@using (Html.BeginForm("ThemMoi","QuanLySanPham",FormMethod.Post,new {@enctype="multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Sách</h4>
        <h3 style="color:red">@ViewBag.ThongBaoKT</h3>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*
        <div class="form-group">
            @Html.LabelFor(model => model.MaSach, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaSach, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.TenSach, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenSach, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenSach, "", new { @class = "text-danger" })
            </div>
        </div>
        <br/>
        <div class="form-group">
            @Html.LabelFor(model => model.GiaBan, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GiaBan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GiaBan, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />
        

        <div class="form-group">
            @Html.LabelFor(model => model.AnhBia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="fileUpload" />
                @*thông báo ảnh đã tồn tại*@
                @ViewBag.ThongBao
            </div>
        </div>
        <br />
        <div class="form-group">
            @Html.LabelFor(model => model.NgayCapNhat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayCapNhat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgayCapNhat, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />
        <div class="form-group">
            @Html.LabelFor(model => model.SoLuongTon, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoLuongTon, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoLuongTon, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />
        <div class="form-group">
            @Html.LabelFor(model => model.MaNXB, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaNXB")
            </div>
        </div>
        <br />
        <div class="form-group">
            @Html.LabelFor(model => model.MaChuDe, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaChuDe")
            </div>
        </div>
        <br />
        <div class="form-group">
            @Html.LabelFor(model => model.Moi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Moi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Moi, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />
        <div class="form-group" style="margin-left:80px">
            @Html.LabelFor(model => model.MoTa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <textarea name="MoTa"></textarea>
            </div>
        </div>

        <div class="form-group"style="margin-left:80px">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div style="color:blue;margin-left:80px">
    @Html.ActionLink("quay trở về", "Index")
</div>

WebApplication4/Views/QuanLySanPham/Xoa.cshtml
@model WebApplication4.Models.Sach

@{
    ViewBag.Title = "Xoa";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}


<h3 style="color:red">Bạn có thực sự muốn xóa quyển sách này ?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MaSach)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaSach)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TenSach)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenSach)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GiaBan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GiaBan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MoTa)
        </dt>

        <dd>
            @Html.Raw(Model.MoTa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AnhBia)
        </dt>

        <dd>
            <img src="@Url.Content("~/HinhAnhSP/"+Model.AnhBia)" width="100" height="150" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgayCapNhat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayCapNhat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoLuongTon)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoLuongTon)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MaNXB)
        </dt>

        <dd>
           @Html.DisplayFor(model => model.NhaXuatBan.TenNXB)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MaChuDe)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ChuDe.TenChuDe)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Moi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Moi)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xóa" class="btn btn-default" /> |
            @Html.ActionLink("Quay trở về", "Index")
        </div>
    }
</div>